version: '2'
services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=opencart
      - MYSQL_ROOT_PASSWORD=change_to_secure_password
    volumes:
      - mysql_data:/var/lib/mysql
  opencart:
    image: aamservices/opencart
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - opencart_data:/var/www/html
    depends_on:
      - mysql
volumes:
  mysql_data:
    driver: local
  opencart_data:
    driver: local

